# -*- coding: utf-8 -*-
"""Copy of Day3FN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144D0uAI-Nnu0l8UBbD5vd1voyHXcOMuS
"""

import torch
import torch.nn as nn

model=nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

